# Generated by Django 5.0.1 on 2024-01-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('forum_link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'DAOs',
            },
        ),
    ]
