# Generated by Django 5.0.1 on 2024-01-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('LastActivityDate', models.DateField()),
                ('OriginalPoster', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Created', models.CharField(blank=True, max_length=255, null=True)),
                ('dao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_links', to='app.dao', to_field='name')),
            ],
            options={
                'db_table': 'ForumLinks',
            },
        ),
    ]
