# Generated by Django 5.0.1 on 2024-01-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_forumlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumlinks',
            name='dao',
        ),
        migrations.AddField(
            model_name='forumlinks',
            name='name',
            field=models.CharField(db_index=True, default='Default Name', max_length=255),
        ),
    ]
