# Generated by Django 5.0.1 on 2024-01-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_forumlinks_dao_forumlinks_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.TextField()),
                ('role', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('total_likes', models.IntegerField(default=0)),
                ('likes', models.TextField(blank=True, null=True)),
                ('total_emoji_reactions', models.IntegerField(default=0, verbose_name='TotalEmojiReactions')),
                ('emoji_reactions', models.TextField(blank=True, null=True, verbose_name='emoji_reactions')),
                ('replies', models.IntegerField(default=0)),
                ('repliers', models.TextField(blank=True, null=True)),
                ('total_replies', models.IntegerField(default=0, verbose_name='TotalReplies')),
                ('post_links', models.TextField(blank=True, null=True)),
                ('link_clicks', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True, verbose_name='Images')),
                ('title', models.TextField(blank=True, null=True)),
                ('post_identifier', models.IntegerField(blank=True, null=True)),
                ('post_id', models.IntegerField(blank=True, null=True, verbose_name='PostID')),
            ],
            options={
                'db_table': 'ForumPosts',
            },
        ),
    ]
