# Generated by Django 5.0.1 on 2024-01-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_forumposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumposts',
            name='post_id',
        ),
    ]
