# Generated by Django 5.0.1 on 2024-01-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_forumposts_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumposts',
            name='post_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='PostID'),
        ),
    ]
