# Generated by Django 5.0.1 on 2024-01-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_forumposts_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumposts',
            name='post_id',
        ),
        migrations.AlterField(
            model_name='forumposts',
            name='emoji_reactions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumposts',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumposts',
            name='total_emoji_reactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumposts',
            name='total_replies',
            field=models.IntegerField(default=0),
        ),
    ]
