# Generated by Django 5.0.1 on 2024-01-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_forumposts_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumposts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
