# Generated by Django 5.0.1 on 2024-01-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_images_forumposts_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumposts',
            old_name='id',
            new_name='PostID',
        ),
    ]
