# Generated by Django 5.0.1 on 2024-05-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_forumposts_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumlinks',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='forumposts',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
