# Generated by Django 5.0.1 on 2024-07-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_forumlinks_wallet_address_forumposts_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumlinks',
            name='Created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumlinks',
            name='LastActivityDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='forumlinks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forumposts',
            name='post_identifier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
