# Generated by Django 5.0.1 on 2024-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_forumlinks_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSummaries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(max_length=500)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('replies', models.IntegerField(blank=True, default=0, null=True)),
                ('LastActivityDate', models.DateField(blank=True, null=True)),
                ('OriginalPoster', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Created', models.DateTimeField(blank=True, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('post_identifier', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'TopicSummaries',
            },
        ),
        migrations.AlterField(
            model_name='forumlinks',
            name='LastActivityDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumlinks',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Default Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forumlinks',
            name='replies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forumlinks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forumlinks',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
